version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/invoice_db
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: invoice_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: